export const MODAL_SHOW = "MODAL_SHOW";
export const MODAL_HIDE = "MODAL_HIDE";

export const OPEN_CREATE_POST_MODAL = "OPEN_CREATE_POST_MODAL";
export const OPEN_EDIT_POST_MODAL = "OPEN_EDIT_POST_MODAL";
export const OPEN_DELETE_POST_MODAL = "OPEN_DELETE_POST_MODAL";