export const GET_MY_POSTS_REQUEST = "GET_MY_POSTS_REQUEST";
export const GET_MY_POSTS_SUCCESS = "GET_MY_POSTS_SUCCESS";
export const GET_MY_POSTS_ERROR = "GET_MY_POSTS_ERROR";

export const GET_ANY_POSTS_REQUEST = "GET_ANY_POSTS_REQUEST";
export const GET_ANY_POSTS_SUCCESS = "GET_ANY_POSTS_SUCCESS";
export const GET_ANY_POSTS_ERROR = "GET_ANY_POSTS_ERROR";

export const GET_LIKED_POSTS_REQUEST = "GET_LIKED_POSTS_REQUEST";
export const GET_LIKED_POSTS_SUCCESS = "GET_LIKED_POSTS_SUCCESS";
export const GET_LIKED_POSTS_ERROR = "GET_LIKED_POSTS_ERROR";

export const GET_FOLLOWED_POSTS_REQUEST = "GET_FOLLOWED_POSTS_REQUEST";
export const GET_FOLLOWED_POSTS_SUCCESS = "GET_FOLLOWED_POSTS_SUCCESS";
export const GET_FOLLOWED_POSTS_ERROR = "GET_FOLLOWED_POSTS_ERROR";

export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_ERROR = "GET_POSTS_ERROR";

export const GET_POST_REQUEST = "GET_POST_REQUEST";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_ERROR = "GET_POST_ERROR";

export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_ERROR = "CREATE_POST_ERROR";

export const EDIT_POST_REQUEST = "EDIT_POST_REQUEST";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_ERROR = "EDIT_POST_ERROR";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_ERROR = "DELETE_POST_ERROR";

export const POST_LIKE_REQUEST = "POST_LIKE_REQUEST";
export const POST_LIKE_SUCCESS = "POST_LIKE_SUCCESS";
export const POST_LIKE_ERROR = "POST_LIKE_ERROR";

export const POST_UNLIKE_REQUEST = "POST_UNLIKE_REQUEST";
export const POST_UNLIKE_SUCCESS = "POST_UNLIKE_SUCCESS";
export const POST_UNLIKE_ERROR = "POST_UNLIKE_ERROR";