export const USER_ME_REQUEST = "USER_ME_REQUEST";
export const USER_ME_SUCCESS = "USER_ME_SUCCESS";
export const USER_ME_ERROR = "USER_ME_ERROR";

export const USER_SETTINGS_REQUEST = "USER_SETTINGS_REQUEST";
export const USER_SETTINGS_SUCCESS = "USER_SETTINGS_SUCCESS";
export const USER_SETTINGS_ERROR = "USER_SETTINGS_ERROR";

export const USER_REQUEST = "USER_REQUEST";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_ERROR = "USER_ERROR";

export const USER_ALL_REQUEST = "USER_ALL_REQUEST";
export const USER_ALL_SUCCESS = "USER_ALL_SUCCESS";
export const USER_ALL_ERROR = "USER_ALL_ERROR";

export const USER_FOLLOWS_REQUEST = "USER_FOLLOWS_REQUEST";
export const USER_FOLLOWS_SUCCESS = "USER_FOLLOWS_SUCCESS";
export const USER_FOLLOWS_ERROR = "USER_FOLLOWS_ERROR";

export const USER_FOLLOWERS_REQUEST = "USER_FOLLOWERS_REQUEST";
export const USER_FOLLOWERS_SUCCESS = "USER_FOLLOWERS_SUCCESS";
export const USER_FOLLOWERS_ERROR = "USER_FOLLOWERS_ERROR";

export const USER_ISFOLLOWED_REQUEST = "USER_ISFOLLOWED_REQUEST";
export const USER_ISFOLLOWED_SUCCESS = "USER_ISFOLLOWED_SUCCESS";
export const USER_ISFOLLOWED_ERROR = "USER_ISFOLLOWED_ERROR";

export const USER_FOLLOW_REQUEST = "USER_FOLLOW_REQUEST";
export const USER_FOLLOW_SUCCESS = "USER_FOLLOW_SUCCESS";
export const USER_FOLLOW_ERROR = "USER_FOLLOW_ERROR";

export const USER_UNFOLLOW_REQUEST = "USER_UNFOLLOW_REQUEST";
export const USER_UNFOLLOW_SUCCESS = "USER_UNFOLLOW_SUCCESS";
export const USER_UNFOLLOW_ERROR = "USER_UNFOLLOW_ERROR";